//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrinksSale.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coin
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Value { get; set; }
        public int Reserve { get; set; }
        public bool IsBlocked { get; set; }
        public int Inserted { get; set; }
        public string Image { get; set; }
    }
}
